# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DataUse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPull_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulldate', models.DateTimeField(auto_now_add=True)),
                ('pullname', models.CharField(max_length=1000)),
                ('pullquery', models.TextField()),
                ('pulltype', models.CharField(choices=[('keyword', 'keyword'), ('author', 'author')], default='', max_length=6)),
                ('pullsource', models.CharField(max_length=255)),
                ('pullby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pulldate',),
            },
        ),
    ]
