# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataUse', '0002_datapull_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapull_id',
            name='pulltype',
            field=models.CharField(choices=[('keyword', 'keyword'), ('author', 'author')], default='', max_length=255),
        ),
    ]
