# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataUse', '0003_auto_20180117_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPull_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedid', models.CharField(max_length=255)),
                ('forename', models.CharField(max_length=1000)),
                ('lastname', models.CharField(max_length=1000)),
                ('contributortype', models.CharField(max_length=255)),
                ('contributorcontact', models.CharField(max_length=255)),
                ('affiliation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataPull_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedid', models.CharField(max_length=255)),
                ('valuestore', models.CharField(choices=[('store', 'store'), ('duplicate', 'duplicate'), ('false positive', 'false positive')], default='', max_length=255)),
                ('note', models.CharField(max_length=1000)),
                ('pubtype', models.CharField(max_length=255)),
                ('pullid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataUse.DataPull_ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataPull_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedid', models.CharField(max_length=255)),
                ('keywordvalue', models.CharField(max_length=255)),
                ('category1', models.CharField(max_length=255)),
                ('category2', models.CharField(max_length=255)),
                ('category3', models.CharField(max_length=255)),
                ('category4', models.CharField(max_length=255)),
                ('category5', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataPull_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associatedid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('journal', models.CharField(max_length=500)),
                ('publicationdate', models.DateField()),
                ('optionalid01', models.CharField(max_length=500)),
                ('optionalid02', models.CharField(max_length=500)),
            ],
        ),
    ]
