# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataUse', '0004_datapull_author_datapull_detail_datapull_keyword_datapull_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
